image: hub.silentcircle.org/eng/sc-android-build

stages:
  - build
  - test
  - deploy

dev_build_job:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_DEBUG_TRACE: "true"
  stage: build
  except: # Except any tags of format vN.M+ or VN.M-rcX
    - /^v\d+\.\d+(\.\d+)*(-rc\d+)?$/
  tags:
    - docker-debian
  script:
    - make
  artifacts:
    name: "dev-${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: on_success
    expire_in: 8 weeks
    paths:
      - silentphone2/build/outputs
  allow_failure: false

beta_build_job:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_DEBUG_TRACE: "true"
  stage: build
  only:
    - /^v\d+\.\d+(\.\d+)*-rc\d+$/
  tags:
    - docker-debian
  script:
    - make
  artifacts:
    name: "beta-${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: on_success
    expire_in: 8 weeks
    paths:
      - silentphone2/build/outputs
  allow_failure: false

prod_build_job:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_DEBUG_TRACE: "true"
  stage: build
  only:
    - /^v\d+\.\d+(\.\d+)*$/
  tags:
    - docker-debian
  script:
    - make
  artifacts:
    name: "prod-${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: on_success
    expire_in: 8 weeks
    paths:
      - silentphone2/build/outputs
  allow_failure: false
